### ISSUE TITLE
data class w/ @Parcelize support for activity intent/fragment argument?

### ISSUE THREAD

**Issue by mochadwi** [idapgroup/ArgumentDelegate#7]
Is it currently possible to use it like this:

```
@Parcelize
MyDataClass(val id: Int, val fullName: String)

val someValue: MyDataClass by argumentDelegate()
```

**Comment by jeketos** [comment]
If your data class will have Parcelable implementation (via @Parcelize or own impl) then yes, it is possible.
Functionality related to the android system restrictions (in this case Bundle)
